# Generated by Django 4.2.9 on 2024-01-31 04:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_salonimage_delete_hairsalonimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyleimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='salonimage',
            name='image',
        ),
        migrations.AddField(
            model_name='hairstyleimage',
            name='hairstyle_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='salonimage',
            name='salon_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
